### ISSUE TITLE
what's different with Xposed

### ISSUE THREAD

**Issue by bjzhou** [alibaba/dexposed#1]
what's different with [Xposed](https://github.com/rovo89/Xposed)?

**Comment by bunnyblue** [comment]
readme不是写的很清楚了吗？xposed需要替换app_process

**Comment by hwjump** [comment]
Xposed need root, and it can hook every process. Dexposed inherit from Xposed, but do something different change to restrict it's powerful ability. Dexposed didn't need root, and it only can hook it's own process, it can't hook other process. So it is suite for single application.
