### ISSUE TITLE
add description for support status(fair/tested/unsure) of android versions in document

### ISSUE THREAD

**Issue by oldratlee** [alibaba/dexposed#10]
Great works!

Could you add description for support status(eg. fair/tested/unsure/unsupported) of each android version in your actual application.

**Comment by pcqpcq** [comment]
this is a good idea

**Comment by oldratlee** [comment]
Thank you for your reply.

As a lib/framework, support status of each android version is very useful when I try to use it, because android os has many version and I need know the support status to decide when is the right time to use this framework.

**Comment by hwjump** [comment]
Sorry for later!  Follow is the support status.
Dalvik runtime
android 2.1/2.2  unsure
android2.3  tested
android3.0  unsure
android4.0-4.4 tested
ART runtime
android 4.4 unsure
android 5.0 testing
android 5.1 unsupported

**Comment by oldratlee** [comment]
please add  support info to readme.md (as  a part of  release note).

and update for each version of dexposed.

**Comment by hwjump** [comment]
Ok， I will change some document for specify the support status！

**Comment by oldratlee** [comment]
Cool! Thanks for your work!
