### ISSUE TITLE
native_dependencies does not work

### ISSUE THREAD

**Issue by ASCE1885** [alibaba/dexposed#19]
Error:Execution failed for task ':app:resolveNativeDependencies'.

> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
> Could not find any matches for com.taobao.dexposed:dexposed_l:0.2+ as no versions of com.taobao.dexposed:dexposed_l are available.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/taobao/dexposed/dexposed_l/maven-metadata.xml
>          https://jcenter.bintray.com/com/taobao/dexposed/dexposed_l/

**Comment by hwjump** [comment]
En, I am studing for how to upload jar and so to jcenter,  If you can help,  a PR is welcome. So current now you can copy jar and so in your project manual.

**Comment by bunnyblue** [comment]
@hwjump   http://inthecheesefactory.com/blog/how-to-upload-library-to-jcenter-maven-central-as-dependency/en  here is docs,simple

**Comment by hwjump** [comment]
Thanks.  

dependencies {
        compile 'com.taobao:dexposed:0.1.0@aar'
}

plz, try again!
