### ISSUE TITLE
dexposed2.3 is missing

### ISSUE THREAD

**Issue by ASCE1885** [alibaba/dexposed#20]
private static boolean loadDexposedLib(Context context) {
    // load xposed lib for hook.
    try {
        if (android.os.Build.VERSION.SDK_INT == 10
                || android.os.Build.VERSION.SDK_INT == 9) {
            System.loadLibrary("dexposed2.3");
        } else if (android.os.Build.VERSION.SDK_INT > 19){
            System.loadLibrary("dexposed_l");
        } else {
            System.loadLibrary("dexposed");
        }
        return true;
    } catch (Throwable e) {
        return false;
    }
}

we could see there is three kind of so file，but there is nowhere to find dexposed2.3

**Comment by pcqpcq** [comment]
duplicate with this: https://github.com/alibaba/dexposed/issues/14

**Comment by ASCE1885** [comment]
thanks，it seems I didn't update my code

**Comment by Eklett** [comment]
Sample 的 dexposedbridge.jar没有更新,里面还是缺少 dexposed2.3 ,查看lib项目的源码后才发现2.3的调用方式已经变了.建议更新sample

**Comment by bunnyblue** [comment]
测试了吗？感觉PLATFORM_SDK_VERSION <14我的鸡dvm很多函数不一样，2.3用的c 4.0+用的c++ 上次测试不成功

**Comment by hwjump** [comment]
Yes， 2.3 ‘s dvm-function was different from 4.0+.  So you need to compile the so in Android2.3 AOSP.

 I didn't have 2.3 compile environment  current now,  So I can't provide it as so far！

If hurry, you can compile it your self. I will provided it later, until I build my compile environment.

**Comment by bunnyblue** [comment]
明天我试试，电脑里面还有2.3分支😄

**Comment by bunnyblue** [comment]
compiled  https://github.com/bunnyblue/dexposed/blob/master/dexposed_so/dexposed_dalvik/target/armeabi/libdexposed2.3.so
