### ISSUE TITLE
为什么不用aar代替呢？

### ISSUE THREAD

**Issue by lizhangqu** [alibaba/dexposed#23]
感觉没有必要使用native_dependencies 啊，直接使用aar不就可以把so包含进来了么

**Comment by hwjump** [comment]
Yes, you are right, we will think about it.

**Comment by hwjump** [comment]
dependencies {
        compile 'com.taobao:dexposed:0.1.0@aar'
}

jcenter

**Comment by tiann** [comment]
failed to resolve: com.taobao:dexposed:0.1.0:

**Comment by hwjump** [comment]
I have uploaded aar to jcenter. I think it may need approval by jcenter for public the binary.  So plz check it later.

**Comment by tiann** [comment]
yes, I use jcenter. but android studio told me that it can not resolve.
I found it on http://bintray.com/hwjump/maven/dexposed.

**Comment by tiann** [comment]
the binary.com tell me that i can use it by:

```
repositories {
    maven {
        url  "http://dl.bintray.com/hwjump/maven" 
    }
}
```

then , i open the url, and found something like this: ../com/taobao/dexposedbridge/0.1.0/
in this directory, i found dexposedbridge-0.1.0.aar. it seems that this aar file is the correct one, may the url be incorrect?

**Comment by hwjump** [comment]
sorry， my mistake， current now， it was still in my maven， I didn't  "Add to JCenter".  I will fix it!

**Comment by hwjump** [comment]
And also, I change the name

dependencies {
compile( 'com.taobao.android:dexposed:0.1.1@aar')
}

so, when jcenter approvel my "Add to JCenter", plz use this dependency.

**Comment by hwjump** [comment]
jcenter approved!

**Comment by tiann** [comment]
@hwjump works like a charm, good job!!
