### ISSUE TITLE
  XposedHelpers.callMethod反射调用bug

### ISSUE THREAD

**Issue by lizhangqu** [alibaba/dexposed#24]
原方法如果是基本数据类型，则无法调用，必须使用包装类

**Comment by hwjump** [comment]
no,  I think you have some mistake.  It support,  this was depedency on the java Reflect api, which was support your case. So could you check your code, plz!  thank you!

**Comment by lizhangqu** [comment]
Oh,I'm so sorry,I have not found there is an override method **public static Object callMethod(Object obj, String methodName, Class<?>[] parameterTypes, Object... args)**，Now,I have solved it!
