### ISSUE TITLE
bus 总线

### ISSUE THREAD

**Issue by join118** [alibaba/dexposed#34]
UI&service & message bus 总线，这个是不是跟业务耦合了？没有开源？ 只开源了runtime 东东?bus 总线解决什么问题？

**Comment by lzwang3d** [comment]
Hi, I wonder where you see the description about UI&service&message bus description.

**Comment by join118** [comment]
hi，我从冯森林的文章中看到的。嘿嘿。

**Comment by hwjump** [comment]
Hey,  Dexposed is an independent project, and it is integrated！It has nothing with “UI&service & message bus” which is another architecture. 

By the way，this is issue list.  Don't ask question in issue list. If you have question, you can chat us in https://gitter.im/alibaba/dexposed. Be greatly appreciated.
