### ISSUE TITLE
Problem In MultiDex

### ISSUE THREAD

**Issue by xk009** [alibaba/dexposed#43]
In MultiDex env, when call System.loadLibrary("dexposed").
throw Couldn't load dexposed from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/xxxx-1.apk" Exception。
I judge that the dexposed class is in the secondary dex。so before call MutilDex.install() ,will cause this case。
I want to know how to use dexposed suitablely in multiDex env.

**Comment by absidibe** [comment]
You're are not obliged...to load dexposed in your class which extends application. you can load where you used it.

**Comment by hwjump** [comment]
You can refer #41
