### ISSUE TITLE
Build.VERSION.SDK_INT >= 21不支持吗

### ISSUE THREAD

**Issue by kingJ430** [alibaba/dexposed#44]
在使用5.0.1手机测试时发现load的是libdexposed_l.so成功
 PatchResult result = PatchMain.load(context, apkPath, null);也返回true
但运行时程序崩溃，请问下现在还不支持5.0(API 21)以上的系统吗？
如果支持该怎么配置？谢谢

**Comment by frank-fan** [comment]
5.x的ART运行环境是在实验阶段，还没有完整支持。

**Comment by wrongch** [comment]
现在Android 6.0 出来好久了，
请问，对于ART运行环境， 什么时候能够完整支持？

**Comment by hwjump** [comment]
You can refer the "dev_art" branch. Thanks
