### ISSUE TITLE
Patch包的依赖问题

### ISSUE THREAD

**Issue by yinglovezhuzhu** [alibaba/dexposed#45]
demo例子中patch是apk包，如果在patch中引用了第三方的库（这个库在程序中已经引用了），是不是必须将第三方的库也要打包到patch包内呢？如果不关联，大不了patch apk包。

**Comment by hwjump** [comment]
No, you can't package the third jar into your patch apk. Or it will cause "java verifyerror".
You can "<scope>provided</scope>" dependency which was "maven" term, this will compile the apk and didn't package the third jar in final apk.

**Comment by yinglovezhuzhu** [comment]
But provided only for jar

**Comment by hwjump** [comment]
Yes， I mean  you use "provided" jar to compile the patch apk, So the patch apk didn't contain the jar, but it can success compiled.
