### ISSUE TITLE
Why can't support YunOS?

### ISSUE THREAD

**Issue by xworks** [alibaba/dexposed#52]
Then we may failed to hook mobiles running on YunOS, is there any explanation? 

```
    public static synchronized boolean isDeviceSupport(Context context) {
        // return memory checked value.
        try {
            if (isCheckedDeviceSupport)
                return isDeviceSupportable;

            if (!isX86CPU() && !isYunOS()) {
                isDeviceSupportable = true;
            } else {
                isDeviceSupportable = false;
            }
        } finally {
            Log.d("hotpatch", "device support is " + isDeviceSupportable + "checked" + isCheckedDeviceSupport);
            isCheckedDeviceSupport = true;
        }
        return isDeviceSupportable;
    }
```

**Comment by hwjump** [comment]
One of the most important feature for YunOS is security， If YunOS has extention for dexposed， it just like a backdoor in YunOS. So YunOs we didn't support!

**Comment by ragnraok** [comment]
Does Alipay use this library?

**Comment by insider-charlie** [comment]
Does Alipay use this library?

**Comment by miao1007** [comment]
Does Alipay use this library?

**Comment by xhmelon** [comment]
Does Alipay use this library?

**Comment by imbible** [comment]
Does Alipay use this library?

**Comment by StoneMoe** [comment]
absolutely

**Comment by hanyuliu** [comment]
Does Alipay use this library?

**Comment by z-wade** [comment]
Does Alipay use this library?

**Comment by anders007** [comment]
Does Alipay use this library?

**Comment by nameoverflow** [comment]
Does Alipay use this library?

**Comment by orvice** [comment]
Does Alipay use this library?

**Comment by CtripmobileOffice** [comment]
本宝宝来解释一下来龙去脉，dexposed是基于xposed，宝宝们都晓得。阿里云OScopy的Android也知道，那时候art还没粗来，阿里云把dvm替换成了收购的虚拟机 🌲🐵，再然后，art粗来了，蓝后，卧槽，直接把art好啊。，拿来grep &&sed  make ，就这样了，不支持云OS了，你们在这儿刷屏有意思吗，这个是手淘的东西，alipay用的andfix，建议把这个话题锁起来，免得骚扰别人。
