### ISSUE TITLE
not be able to replace the method of father class 

### ISSUE THREAD

**Issue by JackCho** [alibaba/dexposed#6]

**Comment by lzwang3d** [comment]
Please point to the father class to hook.

**Comment by lzwang3d** [comment]
The way to find hooked method follows java reflection rule. So point to the father class if want to replace the method in it.

**Comment by JackCho** [comment]
for example, I want to replace getActivity() method with getMyActivity() in a BaseFragment which is a subclass of Fragment. Opoose, how we can deal with this ?

**Comment by lzwang3d** [comment]
Please check if following code for your case:

DexposedBridge.findAndHookMethod(Fragment.class, "getActivity", new XC_MethodHook() {

```
    @Override protected Object beforeHookedMethod(MethodHookParam param) throws Throwable {
        Fragment obj = (Fragment )param.thisObject;
         if (obj instanceof BaseFragment) {
                  // If instance is BaseFragment, call its getMyActivity 
                  BaseFragment base = (BaseFragment )obj;
                   param.setResult(base.getMyActivity());
         }

    }

});
```

**Comment by JackCho** [comment]
@lzwang3d  thanks for the little trick

**Comment by hwjump** [comment]
When you use replace method which need call super method. We provide a new api (invokeSuper() in DexposedBridge) which difference from Xposed. You can use this api in your  XC_MethodReplacement method
