### ISSUE TITLE
How can I load the patch's image resource?

### ISSUE THREAD

**Issue by milk1990** [alibaba/dexposed#65]
In the project, I want to load some new Image,but all of them in the patch package,I use some methods as I know,but it dones't work!

**Comment by hwjump** [comment]
You want patch the resource，first you should hook the AssetManager.addAssetPath() and add your patch resource into system, then you should hook Resources.getDrawable() and TypedArray.getDrawable() and return your patch's image resource. And also you need make sure your patch's image resource has different resource ID number.
These were what I did, hope it could help you.

**Comment by milk1990** [comment]
thanks very mach

**Comment by milk1990** [comment]
thanks very much
