### ISSUE TITLE
Build Issues with AOSP

### ISSUE THREAD

**Issue by azeemsamma** [alibaba/dexposed#66]
[Question]
I have build Android source code successfully and have placed dexposed dalvik code at right places. When I run mmm -B dexposed_dalvik, it starts to compile. But the output is not generated. I have used android-4.3_r2.2.

**Comment by azeemsamma** [comment]
The problem is with LOGI and LOGE.. It cannot find the definition.

**Comment by hwjump** [comment]
Could you paste the error log？
