### ISSUE TITLE
Duplicate files copied in APK

### ISSUE THREAD

**Issue by halilozercan** [alibaba/dexposed#68]
Last summer, I used dexposed library by downloading jar and so files. I guess you moved to Maven repositories and one line dependency works with gradle now. However, I'm facing following error with current version.

```
Error:Execution failed for task ':sample:transformNative_libsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi/libdexposed_l.so
    File1: D:\Works\android-windows\ScreenRecord\sample\build\intermediates\exploded-aar\com.taobao.android\dexposed\0.1.1\jni
    File2: D:\Works\android-windows\ScreenRecord\sample\build\intermediates\exploded-aar\ScreenRecord\library\unspecified\jni
```

**Comment by hwjump** [comment]
It seems there was two copies(libdexposed_l.so) in your project, One is in your local project, Other is in remote repositories(JCenter).   You should only use one.  Hope help!    PS: I only deploy the library to JCenter

**Comment by halilozercan** [comment]
Thanks for replying, I forgot that I opened this issue. I found out what the problem was. As you said, there was a local copy but I could not find it at first. Turns out, it was in jniLibs directory inside app/src/main.
