### ISSUE TITLE
AndFix针对JNI c回调JAVA各种bug，dexposed听说可以hook native层？

### ISSUE THREAD

**Issue by hellokugo** [alibaba/dexposed#69]

**Comment by hwjump** [comment]
dexposed can't hook native code

**Comment by hellokugo** [comment]
感谢回复！
不过想咨询下，dexposed是否支持修改java层的static方法？该方法是项目jni中C回调的方法。

**Comment by hwjump** [comment]
Yes, it can. But current now only support dalvik vm.

**Comment by hellokugo** [comment]
请问什么时候可以支持5.0+呢？
Andfix在这一块好像还有坑
Thx.

**Comment by hwjump** [comment]
You can refer the "dev_art" branch. Thanks
