### ISSUE TITLE
为毛我觉得这项目已经死了。。

### ISSUE THREAD

**Issue by Juude** [alibaba/dexposed#74]

**Comment by pzhangleo** [comment]
感觉基本正确

**Comment by David-Kuper** [comment]
已经死了，确确实实，现在不是AndFix了吗？
- 发送自我的Sony Xperia™智能手机

---- pzhangleo 编写 ----

感觉基本正确

**Comment by pzhangleo** [comment]
阿里内部还在用，可惜就是新的代码不再更新了

**Comment by hwjump** [comment]
You can refer the "dev_art" branch. Thanks

**Comment by yefeidd** [comment]
是的，新的代码已经不更新了
