### ISSUE TITLE
请问dexposed后期还会更新吗？会支持高版本系统吗？

### ISSUE THREAD

**Issue by itliming** [alibaba/dexposed#77]

**Comment by saantiaguilera** [comment]
https://github.com/alibaba/dexposed/issues/74

**Comment by tiann** [comment]
https://github.com/alibaba/dexposed/issues/59

> xposed close some Art compile optimization when dex2oat. that was why xposed can hook View.performClick(), which use EntryPointFromQuickCompiledCode bridge when the method was called. But dexposed can't close compile optimization, so current now it only can hook the method which called using EntryPointFromQuickCompiledCode bridge.

ART会做AOT，会把一些方法编译成native code；Dexposed对被AOT过的方法无能为力。

**Comment by hwjump** [comment]
You can refer the "dev_art" branch. Thanks
